version = 0.1

[default.global.parameters]
stack_name = "ecobot"
resolve_s3 = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false

[default.sync.parameters]
watch = false
dependency_layer = false
